# Generated by Django 6.0.1 on 2026-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_feedback_alter_tagpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
    ]
