# Generated by Django 6.0.1 on 2026-04-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_certificates_sitedescriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedescriptions',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sitedescriptions',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
